name: Package

on:
  push:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Init pants
        uses: pantsbuild/actions/init-pants@v5-scie-pants
        with:
          named-caches-hash: ${{ hashFiles('*/*.sum') }}

      - name: Build
        run: |
          pants package ::
