name: Package

on:
  push:
    paths:
      - "**/*.go"
      - ".github/workflows/package.yml"
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache-dependency-path: app/go.sum

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev
          go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Init pants
        uses: pantsbuild/actions/init-pants@v5-scie-pants
        with:
          named-caches-hash: ${{ hashFiles('*/*.sum') }}

      - name: Build
        run: |
          export BUILDING=yes
          pants run app:build
          pants run app:build-windows
        env:
          BUILDING: yes
