name: Package

on:
  push:
    paths:
      - "**/*.go"
      - ".github/workflows/package.yml"
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache-dependency-path: app/go.sum

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev
          go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Init pants
        uses: pantsbuild/actions/init-pants@v5-scie-pants
        with:
          named-caches-hash: ${{ hashFiles('*/*.sum') }}

      - name: Build
        run: |
          pants run app:build
          pants run app:build-windows
